name: Luis
version: '${project.version}'
main: org.darkexplosiveqwx.luis.Luis
api-version: '1.20'
load: STARTUP
permissions:
  luis.admin:
    description: allows running of administrative commands within luis
    default: op
commands:
  faction:
    description: Choose a Faction between Diamond, Emerald and Netherite by adding it as an Argument.
    usage: /faction <Faction Name, either Diamond,Emerald or Netherithe>
  elect:
    aliases:
      - vote
    description: Elect the King of your Faction.
    usage: /elect <Player Name>
  endvote:
    description: Ends the voting Process.
    usage: /endvote
  king:
    description: Makes a player the king of their faction.
    usage: /king <Player Name>
    permission: luis.admin